### PR TITLE
update to beta5

### PR DESCRIPTION
**Pull request by CrandellWS**
com.android.tools.build:gradle:2.0.0-beta5

Also added CoordinatorLayout.java and AppBarLayout.java

I think it may better better to pull this into a new branch so I created cheese. 

Anyhow this was done because I had an issue with the shadow layer not updating on scroll changes...

Thanks for your work and I hope that this pull request helps save you some of your time. Great Library project!

https://androidreclib.wordpress.com/2015/12/23/lets-port-design-support-library-to-carbon/#more-225

### CODE REVIEW

**Comment by CrandellWS** [comment]
might want to know this was done with a strong focus on API 19 and no care for other API levels

**Comment by ZieIony** [comment]
Thank you for your kind words, I really appreciate that and all help I get from my users!

AppBarLayout and other Design Support Library widgets are available in carbon.beta package. Did you try them? If there's something wrong with them, feel free to open an issue.

**Comment by CrandellWS** [comment]
had not even started to look into the beta source yet...but it functions well in your demo and I am not finding flaws or errors...

I looked at some of your "open issues" and mostly they do not seem like they are actual issues. 

Though I guess I can add to that issueless issue list...

https://github.com/ZieIony/Carbon/issues/196

**Comment by ZieIony** [comment]
This pull request seems to be outdated.

**Pull request closed without merging**
